[package]
name = "pop-launcher"
version = "1.0.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
description = "Library for writing plugins and frontends for pop-launcher"
repository = "https://github.com/pop-os/launcher"
edition = "2018"
resolver = "2"

[workspace]
members = ["bin", "plugins", "service"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "1"
futures-lite = "1"
futures_codec = "0.4"
blocking = "1"
